import React, { useState } from 'react';
import { motion, AnimatePresence } from 'framer-motion';

export default function ForensicReport({ explanation, provenance, isAiGenerated }) {
  const [isExpanded, setIsExpanded] = useState(true);

  // Highlighting key phrases in amber color
  const highlightExplanation = (text) => {
    if (!text) return null;
    const keywords = [
      'deepfake', 'synthetic', 'manipulated', 'high-risk', 'anomaly', 
      'inconsistent', 'gan', 'synthesized', 'artifact', 'authenticity',
      'spectral gaps', 'temporal inconsistency', 'mesh mismatch'
    ];
    let highlighted = text;
    keywords.forEach(word => {
      const regex = new RegExp(`(${word})`, 'gi');
      highlighted = highlighted.replace(regex, '<span class="text-amber-500 font-bold">$1</span>');
    });
    return <p className="text-gray-600 leading-relaxed font-serif italic text-lg" dangerouslySetInnerHTML={{ __html: highlighted }} />;
  };

  return (
    <div className="bg-white/60 backdrop-blur-xl border border-white/40 rounded-[2.5rem] overflow-hidden shadow-[0_8px_30px_rgb(0,0,0,0.04)] hover:border-black/5 transition-all">
      <div 
        className="px-8 py-6 flex items-center justify-between cursor-pointer bg-gray-50/50"
        onClick={() => setIsExpanded(!isExpanded)}
      >
        <div className="flex items-center gap-3">
          <span className="material-symbols-outlined text-amber-500">biotech</span>
          <h3 className="text-[0.75rem] font-bold uppercase tracking-[0.2em] text-black">Forensic Breakdown</h3>
        </div>
        <span className={`material-symbols-outlined transition-transform duration-300 ${isExpanded ? 'rotate-180' : ''}`}>
          expand_more
        </span>
      </div>

      <AnimatePresence>
        {isExpanded && (
          <motion.div 
            initial={{ height: 0, opacity: 0 }}
            animate={{ height: 'auto', opacity: 1 }}
            exit={{ height: 0, opacity: 0 }}
            className="overflow-hidden"
          >
            <div className="p-10 space-y-14 border-t border-gray-50/50">
              {/* Explanation Section */}
              <section>
                <div className="flex items-center gap-2 mb-4">
                  <span className="size-1.5 bg-amber-500 rounded-full" />
                  <h4 className="text-[0.65rem] font-bold text-gray-400 uppercase tracking-widest">Neural Consensus Explanation</h4>
                </div>
                {isAiGenerated && (
                  <motion.div 
                    initial={{ scale: 0.95, opacity: 0 }}
                    animate={{ scale: 1, opacity: 1 }}
                    className="mb-8 p-6 bg-purple-50/50 border border-purple-100 rounded-2xl flex items-start gap-4"
                  >
                    <div className="size-10 rounded-xl bg-purple-100 flex items-center justify-center text-purple-600 shrink-0">
                      <span className="material-symbols-outlined">auto_awesome</span>
                    </div>
                    <div>
                      <h5 className="text-[0.8rem] font-bold text-purple-900 uppercase tracking-wider mb-1">Synthetically Autogenerated Content</h5>
                      <p className="text-[0.85rem] text-purple-700 leading-relaxed font-medium">
                        This content appears to be fully AI-generated, not manipulated from real footage. High confidence markers for neural synthesis detected.
                      </p>
                    </div>
                  </motion.div>
                )}
                {highlightExplanation(explanation || "Analysis pending detailed report generation.")}
              </section>

              {/* Provenance Timeline Section */}
              <section>
                <div className="flex items-center gap-3 mb-10">
                  <span className="size-1.5 bg-gray-300 rounded-full" />
                  <h4 className="text-[0.7rem] font-bold text-gray-400 uppercase tracking-[0.2em]">Provenance Timeline</h4>
                </div>
                
                <div className="relative pl-10 space-y-10 before:absolute before:left-[11px] before:top-2 before:bottom-2 before:w-[1px] before:bg-gray-100">
                  {(provenance && provenance.length > 0 ? provenance : [
                    { label: 'Asset Ingestion', detail: 'File received and staged for forensic evaluation.', risk: 'low', timestamp: 'T+0ms' },
                    { label: 'Neural Scan', detail: 'Face mesh and spectral stability checks initiated.', risk: 'medium', timestamp: 'T+400ms' },
                    { label: 'Consensus Reached', detail: 'Multi-model verification complete.', risk: 'low', timestamp: 'T+1200ms' }
                  ]).map((event, i) => (
                    <div key={i} className="relative group">
                      <motion.div 
                        initial={{ scale: 0 }}
                        animate={{ scale: 1 }}
                        transition={{ delay: 0.1 * i }}
                        className={`absolute -left-[32px] top-1 size-[24px] rounded-full border-4 border-white shadow-md ring-1 ring-black/5 ${
                          event.risk === 'high' ? 'bg-red-500' : 
                          event.risk === 'medium' ? 'bg-amber-500' : 
                          'bg-emerald-500'
                        }`} 
                      />
                      <div className="flex flex-col gap-1 group-hover:translate-x-1 transition-transform">
                        <div className="flex items-center justify-between">
                          <span className="text-[1rem] font-bold text-black font-serif">{event.label}</span>
                          <span className="text-[0.7rem] font-mono text-gray-300 font-bold">{event.timestamp}</span>
                        </div>
                        <p className="text-[0.85rem] text-gray-500 leading-relaxed max-w-xl">{event.detail}</p>
                      </div>
                    </div>
                  ))}
                </div>
              </section>
            </div>
          </motion.div>
        )}
      </AnimatePresence>
    </div>
  );
}
